# Generated by Django 2.0.6 on 2020-07-11 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.BaseModel')),
                ('title', models.CharField(max_length=200, verbose_name='导航标题')),
                ('link', models.CharField(max_length=300, verbose_name='导航链接')),
                ('position', models.IntegerField(choices=[(1, '顶部导航'), (2, '底部导航')], default=1, verbose_name='导航位置')),
                ('is_site', models.BooleanField(default=False, verbose_name='是否是外部链接')),
            ],
            options={
                'verbose_name': '尾栏',
                'verbose_name_plural': '尾栏',
                'db_table': 'bz_footer',
            },
            bases=('home.basemodel',),
        ),
    ]
